[tox]
envlist = py310, py311, py312
skip_missing_interpreters = true
isolated_build = false

[testenv]
description = Run pytest for {envname}
setenv =
    PIP_EXTRA_INDEX_URL = https://download.pytorch.org/whl/cpu
deps =
    -rrequirements.txt
commands =
    python -m pytest -q
